name: Release

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set tag and directory name env
      run: |
        $tagName = $Env:GITHUB_REF -replace 'refs/tags/', ''
        $dirName = "GD3D11"
        $shortHash = $Env:GITHUB_SHA.Substring(0, 9)
        echo "Tag: ${tagName}"
        echo "Directory: ${dirName}"
        echo "RELEASE_VERSION=${tagName}" >> $Env:GITHUB_ENV
        echo "RELEASE_DIR=${dirName}" >> $Env:GITHUB_ENV
        echo (-join("CL=/DVERSION_NUMBER#",'\"',"${tagName}-${shortHash}",'\"')) >> $Env:GITHUB_ENV

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore .

    - name: Build G2 NotR AVX2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Release_G2A_AVX2 .

    - name: Build G2 NotR AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Release_G2A_AVX .

    - name: Build G1 AVX2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Release_G1_AVX2 .

    - name: Build G1 AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Release_G1_AVX .

    - name: Build G2 NotR
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Release_G2A_SSE2 .

    - name: Build G1
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Release_G1_SSE2 .
      
      name: Build G1 Sequel AVX2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Release_G1A_AVX2 .

    - name: Build G1 Sequel AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Release_G1A_AVX .
      
    - name: Build G1 Sequel
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Release_G1A_SSE2 .

    - name: Build Launcher
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Launcher .

    - name: Create distribution zip
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir "${{env.RELEASE_DIR}}\GD3D11\shaders\CSFFT" -Force
        mkdir "${{env.RELEASE_DIR}}\GD3D11\Bin" -Force
        Xcopy "D3D11Engine\Shaders\*" "${{env.RELEASE_DIR}}\GD3D11\shaders" /s
        copy "D3D11Engine\CSFFT\*.hlsl" "${{env.RELEASE_DIR}}\GD3D11\shaders\CSFFT"
        Xcopy "blobs\Meshes" "${{env.RELEASE_DIR}}\GD3D11\Meshes\" /s
        Xcopy "blobs\Textures" "${{env.RELEASE_DIR}}\GD3D11\Textures\" /s
        Xcopy "blobs\Fonts" "${{env.RELEASE_DIR}}\GD3D11\Fonts\" /s
        Xcopy "blobs\libs\*" "${{env.RELEASE_DIR}}\" /s
        copy "Release_G2A_AVX2\ddraw.dll" "${{env.RELEASE_DIR}}\GD3D11\Bin\g2a_avx2.dll"
        copy "Release_G2A_AVX\ddraw.dll" "${{env.RELEASE_DIR}}\GD3D11\Bin\g2a_avx.dll"
        copy "Release_G2A_SSE2\ddraw.dll" "${{env.RELEASE_DIR}}\GD3D11\Bin\g2a.dll"
        copy "Release_G1_AVX2\ddraw.dll" "${{env.RELEASE_DIR}}\GD3D11\Bin\g1_avx2.dll"
        copy "Release_G1_AVX\ddraw.dll" "${{env.RELEASE_DIR}}\GD3D11\Bin\g1_avx.dll"
        copy "Release_G1_SSE2\ddraw.dll" "${{env.RELEASE_DIR}}\GD3D11\Bin\g1.dll"
        copy "Release_G1A_AVX2\ddraw.dll" "${{env.RELEASE_DIR}}\GD3D11\Bin\g1a_avx2.dll"
        copy "Release_G1A_AVX\ddraw.dll" "${{env.RELEASE_DIR}}\GD3D11\Bin\g1a_avx.dll"
        copy "Release_G1A_SSE2\ddraw.dll" "${{env.RELEASE_DIR}}\GD3D11\Bin\g1a.dll"
        cd "${{env.RELEASE_DIR}}"
        7z a -tzip "..\${{env.RELEASE_DIR}}.zip" -r

    - name: Calculate distribution zip hash
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        (Get-FileHash "${{env.RELEASE_DIR}}.zip" -Algorithm SHA256).hash | Out-File -FilePath "${{env.RELEASE_DIR}}.zip.sha256"
        type "${{env.RELEASE_DIR}}.zip.sha256"

    - name: Create github release
      run: |
        gh release create ${{env.RELEASE_VERSION}} -n "Generated release from GitHub Actions"
        echo "Ignore 'Validation Failed' results. Expected since only the first job that reaches this step can create the release."
        exit 0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Upload artifacts to github release
      run: |
        gh release upload ${{env.RELEASE_VERSION}} "${{env.RELEASE_DIR}}.zip"
        gh release upload ${{env.RELEASE_VERSION}} "${{env.RELEASE_DIR}}.zip.sha256"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
